#!/usr/bin/env python
# -*- coding: utf-8

import os
import sys


def main():
    try:
        cmd = sys.argv[1]
    except IndexError:
        sys.exit('manage takes at least one argument')
    if cmd == 'test':
        syscmd = (
            'nosetests --with-coverage --cover-package=pywebstack '
            '{args}'.format(args=' '.join(sys.argv[2:]))
        )
        os.system(syscmd)
    else:
        os.system('sudo PYTHONPATH={d} bin/{cmd} {args}'.format(
            d=os.path.dirname(__file__),
            cmd=cmd,
            args=' '.join(sys.argv[2:])
        ))


if __name__ == '__main__':
    main()
