#!/usr/bin/env python
# -*- coding: utf-8

import os
import sys


def run(cmd):
    code = os.system(cmd)
    if code:
        sys.exit(1)
    sys.exit()


def main():
    try:
        cmd = sys.argv[1]
    except IndexError:
        sys.exit('manage takes at least one argument')
    if cmd == 'test':
        run('nosetests -c .noserc {extra_args}'.format(
            extra_args=' '.join(sys.argv[2:])
        ))
    else:
        run('sudo PYTHONPATH={d} bin/{cmd} {args}'.format(
            d=os.path.dirname(__file__),
            cmd=cmd,
            args=' '.join(sys.argv[2:])
        ))


if __name__ == '__main__':
    main()
